[tool.poetry]
name = "csql"
version = "0.1.0"
description = ""
authors = ["Jarrad Whitaker <akdor1154@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = {version = "^0.7", python = "<3.7"}

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
